<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="classLayout2Frontend" nsURI="http://www.classlayout2frontend.com/classLayout2Frontend"
    nsPrefix="classLayout2Frontend">
  <eClassifiers xsi:type="ecore:EClass" name="Project">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="entitiesmodel" eType="#//EntitiesModel"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="siteViews" upperBound="-1"
        eType="#//SiteView" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="pageViews" upperBound="-1"
        eType="#//PageView" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="containerViews" upperBound="-1"
        eType="#//ContainerView" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Composition" eSuperTypes="#//Association"/>
  <eClassifiers xsi:type="ecore:EClass" name="Association" abstract="true" eSuperTypes="#//StructuralFeature">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="many" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="target" lowerBound="1"
        eType="#//Entity"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PropertyType" abstract="true" eSuperTypes="#//EntityModelElement"/>
  <eClassifiers xsi:type="ecore:EClass" name="Property" eSuperTypes="#//StructuralFeature">
    <eStructuralFeatures xsi:type="ecore:EReference" name="type" lowerBound="1" eType="#//PropertyType"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="defaultValue" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="StructuralFeature" abstract="true" eSuperTypes="#//EntityModelElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="required" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EntitiesModel">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="modelElements" upperBound="-1"
        eType="#//EntityModelElement" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EntityModelElement" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        iD="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="description" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="displayName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Entity" eSuperTypes="#//EntityModelElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="superclass" eType="#//Entity"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isAbstract" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="structuralFeatures" upperBound="-1"
        eType="#//StructuralFeature" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PrimitiveType" eSuperTypes="#//PropertyType"/>
  <eClassifiers xsi:type="ecore:EClass" name="Literal" eSuperTypes="#//EntityModelElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Enumeration" eSuperTypes="#//PropertyType">
    <eStructuralFeatures xsi:type="ecore:EReference" name="literals" upperBound="-1"
        eType="#//Literal" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Reference" eSuperTypes="#//Association"/>
  <eClassifiers xsi:type="ecore:EClass" name="AtomicView" abstract="true" eSuperTypes="#//ElementView">
    <eStructuralFeatures xsi:type="ecore:EReference" name="property" eType="#//StructuralFeature"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Autocomplete" eSuperTypes="#//Selection">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="multiple" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Dropdownlist" eSuperTypes="#//Selection"/>
  <eClassifiers xsi:type="ecore:EClass" name="Image" eSuperTypes="#//Output">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="width" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="height" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="List" eSuperTypes="#//Selection">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="multiple" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Output" abstract="true" eSuperTypes="#//AtomicView"/>
  <eClassifiers xsi:type="ecore:EClass" name="IterationFilter">
    <eStructuralFeatures xsi:type="ecore:EReference" name="input" eType="#//Input"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="InputText" eSuperTypes="#//Input">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="multiline" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PageView">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="elementViews" upperBound="-1"
        eType="#//ElementView"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="layoutType" eType="#//LayoutType"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SiteView">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="templateName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="templateColor" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="displayName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="pageViews" upperBound="-1"
        eType="#//PageView"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="StaticContainer" eSuperTypes="#//ContainerView"/>
  <eClassifiers xsi:type="ecore:EEnum" name="LayoutType">
    <eLiterals name="SINGLE_COLUMN"/>
    <eLiterals name="TWO_COLUMNS" value="1"/>
    <eLiterals name="LEFT_BAR" value="2"/>
    <eLiterals name="RIGHT_BAR" value="3"/>
    <eLiterals name="THREE_COLUMNS" value="4"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TextArea" eSuperTypes="#//Output">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isTitle" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Selection" abstract="true" eSuperTypes="#//Input"/>
  <eClassifiers xsi:type="ecore:EClass" name="Input" abstract="true" eSuperTypes="#//AtomicView">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="label" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="IterationContainer" eSuperTypes="#//ContainerView">
    <eStructuralFeatures xsi:type="ecore:EReference" name="iterationFilters" upperBound="-1"
        eType="#//IterationFilter" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="InputForm" eSuperTypes="#//ContainerView"/>
  <eClassifiers xsi:type="ecore:EClass" name="CheckList" eSuperTypes="#//Selection"/>
  <eClassifiers xsi:type="ecore:EClass" name="ElementView" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="displayName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="description" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RadioButtonGroup" eSuperTypes="#//Selection"/>
  <eClassifiers xsi:type="ecore:EClass" name="ContainerView" abstract="true" eSuperTypes="#//ElementView">
    <eStructuralFeatures xsi:type="ecore:EReference" name="elements" upperBound="-1"
        eType="#//ElementView" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="entity" eType="#//Entity"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FileUpload" eSuperTypes="#//Input"/>
</ecore:EPackage>